:- module(server, [server/1]).

:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_error)).
:- use_module(library(http/html_write)).
:- use_module(library(http/http_parameters)).

server(Port) :-
        http_server(http_dispatch, [port(Port)]).


:- http_handler('/', web_form, []).
:- http_handler('/minimaleSammlung', landing_pad, []).

web_form(_Request) :-
	reply_html_page(
	title('MinimaleSammlungDialog'), 
	[
	  form([action='/minimaleSammlung', method='post'], [
	  	h1(['Empfohlene Handlungen um bestimmten Stoff zu erhalten']),
	    p([], [input([name='anzahl', type='text', value='', size='24'])]),
        p([], [\['<select name="stoffAuswahl" size="1" id="StoffAuswahl">
    <option>absprungKapselKoordinaten
    <option>angereicherterKohlenStoff
    <option>aktiviertesCadmium
    <option>aktiviertesEmeril
    <option>aktiviertesIndium
    <option>aktiviertesKupfer
    <option>ammoniak
    <option>antiHaftKolben
    <option>antiMaterie
    <option>antiMaterieGehaeuse
    <option>aronium
    <option>ausrangierteSchaltPlatte
    <option>autonomePositionierungsEinheit
    <option>beutelGift
    <option>bromSalz
    <option>cadmium
    <option>chlor
    <option>chlorGitter
    <option>chromatischesMetall
    <option>faecium
    <option>deuterium
    <option>dioxit
    <option>diWasserStoff
    <option>diWasserStoffGelee
    <option>dunkleMaterie
    <option>eiweissPerle
    <option>emeril
    <option>endeDerDaemmerung
    <option>entschluesselteBenutzerDaten
    <option>erstGebruetetenHelm
    <option>experimentelleEnergieFluessigkeit
    <option>ferritStaub
    <option>frischeFlutPalmenSprossen
    <option>frostKristall
    <option>fluessigSprengStoff
    <option>fortschrittlicherIonenAkku
    <option>fregattenTreibStoff100to
    <option>fregattenTreibStoff200to
    <option>fregattenTreibStoff50to
    <option>fuenfDimensionalerTorus
    <option>funkenKanister
    <option>fusionsBeschleuniger
    <option>fusionsZuender
    <option>gammaWurzel
    <option>gefangeneNanode
    <option>gekNip
    <option>gekRelikt
    <option>geoDesit
    <option>gewaltigesMetallZahnRad
    <option>glas
    <option>gold
    <option>grantine
    <option>gravitinoBall
    <option>halbLeiter
    <option>heissesEis
    <option>hermetischesSiegel
    <option>herox
    <option>herzDerSonne
    <option>hitzeKondensator
    <option>holografischerAnalysator
    <option>holographischeKurbelWelle
    <option>hypnotischenTraenken
    <option>hydrothermaleTreibStoffZelle
    <option>indium
    <option>industrieBatterie
    <option>instabilesGel
    <option>instabilesNatrium
    <option>instabilesPlasma
    <option>instabilitaetsInjektor
    <option>ionenAkku
    <option>ionenKugel
    <option>ionenKondensator
    <option>ionisiertesKobalt
    <option>iridesit
    <option>kaktusFleisch
    <option>kampfLaeuferGehirn
    <option>kelpBeutel
    <option>kobalt
    <option>kobaltSpiegel
    <option>kohlenStoff
    <option>kohlenStoffKristall
    <option>kohlenStoffNanoRohr
    <option>kometenTroepfchen
    <option>korvaxGehaeuse
    <option>korvaxKonvergenzWuerfel
    <option>kristallSulfid
    <option>kryogenKammer
    <option>kryoPumpe
    <option>kuerbisKnolle
    <option>kupfer
    <option>lebendePerle
    <option>lebenderSchleim
    <option>lebendesGlas
    <option>lebensErhaltungsGel
    <option>lemmium
    <option>magnetisiertesFerrit
    <option>magnoGold
    <option>metallPlatten
    <option>mikroProzessor
    <option>modifizierteQuanten
    <option>mordit
    <option>nanitHaufen
    <option>nanoRohrKiste
    <option>natrium
    <option>natriumDiode
    <option>natriumNitrat
    <option>navigationsDaten
    <option>neuralLeitung
    <option>neutronenMikroskop
    <option>nichtMehrDuftendePheromonFlasche
    <option>nipNipKnospen
    <option>nooSpaerischKugel
    <option>novaeRegenerat
    <option>organischerKatalysator
    <option>ohmschesGel
    <option>optischesLoesungsMittel
    <option>organischeRohre
    <option>paraffinium
    <option>phasenStrahler
    <option>phosphor
    <option>photischerJade
    <option>pilzSchimmel
    <option>platin
    <option>polyFaser
    <option>polyChronesZirkonium
    <option>projektilMunition
    <option>pugneum
    <option>pyrit
    <option>quantumBeschleuniger
    <option>quantumProzessor
    <option>radon
    <option>raumSchiffStartTreibStoff
    <option>reinesFerrit
    <option>restSubstanz
    <option>saeure
    <option>salz
    <option>salzRefaktor
    <option>sauerStoff
    <option>sauerStoffFilter
    <option>sauerStoffKapsel
    <option>schaltPlatte
    <option>schmierMittel
    <option>schmutz
    <option>schwefelin
    <option>schweisserSeife
    <option>silber
    <option>solanium
    <option>sternenKnolle
    <option>stickStoff
    <option>sechsZackigerEntKoppler
    <option>seltenesMetallElement
    <option>sichSelbsReparierendesHeridium
    <option>sternenSeide
    <option>stickStoffSalz
    <option>strassenKoeterBronze
    <option>superOxidKristall
    <option>supraLeiter
    <option>supraleitendeFaser
    <option>kabelBaum
    <option>teleportKoordinaten
    <option>tetraKobalt
    <option>thermischesKondensat
    <option>tragbarerReaktor
    <option>tritium
    <option>umhuellterSchatten
    <option>unkontrollierbarerSchimmel
    <option>unraffiniertesPyritFett
    <option>uran
    <option>verdichteterKohlenStoff
    <option>vergitterterBogenKristall
    <option>verrostetesMetall
    <option>vierfachServo
    <option>vyKeenBildnis
    <option>vyKeenDolch
    <option>warpZelle
    <option>waermeSchutzModulS
    <option>wirbelWuerfel
    <option>wiederhergestellteTechnologie
    <option>zaeheFluessigkeiten
    <option>zustandsPhase
    <option>zytoPhosphat
    <option>atlasPassV1
    <option>atlasPassV2
    <option>atlasPassV3
    <option>sternenSamen
    <option>ammoniumHaltigeVerarbeitungsAnlagen
    <option>effizienteWasserduesenA
    <option>effizienteWasserduesenB
    <option>effizienteWasserduesenC
    <option>effizienteWasserduesenS
    <option>gefahrenSchutz
    <option>gefahrGutSchutzHandschuh
    <option>jetPack
    <option>neuralStimulator
    <option>qFeldInternePolsterung
    <option>raketenStiefel
    <option>sauerstoffHaltigeStabilisatoren
    <option>sauerstoffUmleiterA
    <option>sauerstoffUmleiterB
    <option>sauerstoffUmleiterC
    <option>sauerstoffUmleiterS
    <option>sauerstoffWiederVerwerterC
    <option>selbstReinigendeKiemenEinheit
    <option>schildGitter
    <option>unterHyperDruckStehendeKreislaufAtmungsHilfe
    <option>frachterHyperAntrieb
    <option>infraMesser
    <option>asymetrischeRefraktoren
    <option>chromatischeSplitter
    <option>dauerwelligePolarisatoren
    <option>freiElektronischeOszillatoren
    <option>glorreicheNeutrinoInjektoren
    <option>gyroskopischeEntfernungsPolarisatoren
    <option>gyroskopischePlasmaAuspuffRohre
    <option>hypersonischeNeutrinoInjektoren
    <option>induktiveResonatoren
    <option>nuklearePolarisatoren
    <option>resonanteReflektorGlaeser
    <option>spezialisierteSuperLuminare
    <option>supraleitendeReflektorGlaeser
    <option>unvergleichlicheReflektorGlaeser
    <option>ultraHochfrequenteOszillatoren
    <option>gedankenKontrollGeraet
    <option>holographischerAnalysator
    <option>mineralKompressor
    <option>sprengDrohnen
    <option>treibStoffOxidant
    <option>analyseVisier
    <option>gammaStrahlendeBegrenzer
    <option>scanner
    <option>wellenFormWiederVerwerter
    <option>terrainManipulator
    <option>eigenesKraftFeld
    <option>kampfVisier
    <option>minenLaser
    <option>fortgeschrittenerMinenLaser
    <option>blitzWerfer
    <option>laufIonisator
    <option>plasmaWerfer
    <option>geologieKanone
    <option>glutSpeer
    <option>masseBeschleuniger
    <option>streuBlaster
    <option>geschossSchmierer
    <option>impulsWerfer
    <option>verstaerkteKartuschen
    <option>fusionsAntrieb
    <option>humboldtAntrieb
    <option>driftAufhaengung
    <option>haftungsVerstaerkungsAufhaengung
    <option>rutschAufhaengung
    <option>exoFahrzeugBordKanonenUpgrade
    <option>exoFahrzeugMinenLaserUpgrade
    <option>exoFahrzeugSignalBooster
    <option>exoFahrzeugSignalBoosterUpgradeSigma
    <option>exoFahrzeugSignalBoosterUpgradeTau
    <option>exoFahrzeugBeschleunigungsModul
    <option>exoFahrzeugMinenLaser
    <option>exoFahrzeugMinenLaserUpgradeSigma
    <option>exoFahrzeugBordKanone
    <option>nautilonKanone
    <option>tethysStrahl
    <option>osmotischerGenerator
    <option>konstruktionsTerminal
    <option>exoFahrzeugTerminal
    <option>waffenTerminal
    <option>wissenschaftsTerminal
    <option>landwirtschaftsTerminal
    <option>lagerBehaelter1
    <option>verschlosseneKiste
    <option>floraBehaelterTubus
    <option>hydroKulturTrog
    <option>grosserHydroKulturTrog
    <option>magenKrampfBlume
    <option>echinoKaktus
    <option>frostWurz
    <option>gammaGras
    <option>giftIgel
    <option>gravitinoWirt
    <option>morditWurzel
    <option>pilzGeflecht
    <option>sonnenRebe
    <option>sternenDorn
    <option>kollossGeoBucht
    <option>nomadenGeoBucht
    <option>roamerGeoBucht
    <option>atmosphaerenVerarbeitungsAnlage
    <option>autonomeBergBauEinheit
    <option>basisComputer
    <option>konstruktionsForschungsStation
    <option>kommunikationsStation
    <option>nachrichtenModul
    <option>speicherSignalTragbar
    <option>signalBooster
    <option>speicherPunkt
    <option>tragbareRaffinerie
    <option>basisBergungsKapsel
    <option>basisTelePorterModul
    <option>terminalDesGalaktischenMarktes
    <option>gefahrenSchutzEinheit
    <option>gesundheitsStation
    <option>grosseRaffinerie
    <option>bett
    <option>licht
    <option>farbigeLeuchte
    <option>farbigeLeuchteGruen
    <option>farbigeLeuchteRot
    <option>farbigeLeuchteWeiss
    <option>flagge2
    <option>tiefSeeKammer
    <option>glasPlatteMitHolzRahmen
    <option>holzBodenPlatte
    <option>holzDach
    <option>holzFenster
    <option>holzRampe
    <option>holzTuerRahmen
    <option>holzWand
    <option>betonWand
    <option>korridorFenster
    <option>metallFenster
    <option>metallWand
    <option>zylindrischerRaum
    <option>achtEckSchrank
    <option>arbeitsPlatte
    <option>aussehenModifikator
    <option>betonBodenPlatte
    <option>betonBogen
    <option>betonDach
    <option>betonDachEckStueck
    <option>betonDachPlatte
    <option>betonTuer
    <option>betonTuerRahmen
    <option>duenneBetonWand
    <option>duenneMetallWand
    <option>dekor
    <option>eckSofa
    <option>ergonomischesSofa
    <option>einfacherSchreibTisch
    <option>fundament
    <option>gebogenerKorridor
    <option>gebogenesRohr
    <option>geraderKorridor
    <option>gewoelbteWuerfelFoermigeWand
    <option>glasPlatteMitBetonRahmen
    <option>glasPlatteMitMetallRahmen
    <option>grossesGlasPaneel
    <option>grosserKeil
    <option>gruenerWandBildSchirm
    <option>halberBetonBogen
    <option>halberHolzBogen
    <option>halberMetallBogen
    <option>hoherSchrank
    <option>infraStrukturLeiter
    <option>kanisterRegal
    <option>kleineBetonBodenPlatte
    <option>kleineBetonWand
    <option>kleineHolzWand
    <option>kleineHolzPlatte
    <option>kleineMetallPlatte
    <option>kleineMetallWand
    <option>kleineKiste
    <option>kleinerKeil
    <option>kurzeBetonWand
    <option>kurzeHolzWand
    <option>kurzeMetallWand
    <option>kugel
    <option>laborLampe
    <option>lagerModulDeko
    <option>leiter
    <option>lFoermigerKorridor
    <option>metallBodenPlatte
    <option>metallBogen
    <option>metallTuer
    <option>orangeFarbenerWandBildSchirm
    <option>oszilloskop
    <option>pflasterungVierFach
    <option>pflasterung
    <option>pflasterung3
    <option>pyramide
    <option>quadratischerRaum
    <option>quadratischeTiefSeeKammer
    <option>regalModul
    <option>rennHindernis
    <option>roboterArm
    <option>rohr
    <option>schliessFach
    <option>schraegeBetonPlatte
    <option>schraegeHolzPlatte
    <option>schraegeMetallPlatte
    <option>schubLadenSchrank
    <option>sofa
    <option>stabilerWuerfel
    <option>stuhl1
    <option>stuhl2
    <option>stuhl3
    <option>tFoermigerKorridor
    <option>tisch1
    <option>tisch2
    <option>topfPflanze
    <option>tuer
    <option>wuerfel
    <option>wuerfelFoermigeInnenTuer
    <option>wuerfelFoermigerDachAufsatz
    <option>wuerfelFoermigerRaum
    <option>wuerfelFoermigerRaumBoden
    <option>wuerfelFoermigerRaumRahmen
    <option>fundamentStrebe
    <option>viererFundametStrebe
    <option>xFoermigerKorridor
    <option>zylinder
    <option>zylindrischerRaumRahmen
    <option>aussichtsKugel
    <option>betonFassade
    <option>betonFenster
    <option>betonRampe
    <option>bioKuppelRaum
    <option>bodenMatte
    <option>deckenLeuchte
    <option>deckenPaneel
    <option>fassFoermigerFabrikator
    <option>fenster
    <option>flachesModul
    <option>gewoelbtesWuerfelFoermigesDach
    <option>grosseMonitorStation
    <option>halbeBetonRampe
    <option>halbeHolzRampe
    <option>halbeMetallRampe
    <option>holoTuer
    <option>holzDachEndStueck
    <option>holzDachPlatte
    <option>holzFassade
    <option>innenTreppen
    <option>kistenFoermigerFabrikator
    <option>korridorMitGlasDach
    <option>lagerBehaelter
    <option>leichterTisch
    <option>metallDach
    <option>metallDachEckStueck
    <option>metallDachPlatte
    <option>metallFassade
    <option>metallRampe
    <option>mittlereRaffinerie
    <option>monitorStation
    <option>rennKraftVerstaerker
    <option>seitenModul
    <option>server
    <option>techBedienFeld
    <option>waffenRegal
    <option>wandBildSchirm
    <option>wandEinheit
    <option>wandVentilator
    <option>wasserDichteTuer
    <option>wuerfelFoermigerGlasRaum
    <option>zugangsRampe
    <option>exoFahrzeugBeschleunigungsModulA
    <option>exoFahrzeugBeschleunigungsModulB
    <option>exoFahrzeugSignalBoosterUpgrade
    <option>exoFahrzeugSignalBoosterUpgradeA
    <option>glasTunnel
    <option>kolossGeoBucht
    <option>landeFeld
    <option>lFoermigerGlasTunnel
    <option>meeresUnterSchlupf
    <option>nautilonKammer
    <option>sauerStoffVerarbeiter
    <option>tFoermigerGlasTunnel
    <option>vertikalerGlasTunnel
    <option>wasserDichteTuer1
  </select>']]),
        p([], [input([name='Submit', type='submit', value='OK'])])
	  ])
	]).

landing_pad(Request) :-
        member(method(post), Request), !,
        /*http_read_data(Request, Data, []),*/
        format('Content-type: text/html~n~n', []),
		/*portray_clause(Data),*/
		/* portray_clause(Request), */
		http_parameters(Request, [
          anzahl(AtomAnzahl, [default('1')]),
          stoffAuswahl(Stoff, [length > 1])
        ]),
        atom_number(AtomAnzahl, Anzahl),
        format('<table width="20%" border="1">
			  <caption>
			    <h2>Eingaben</h2>
			  </caption>
			  <tr>
			    <th scope="col">Anzahl&nbsp;</th>
			    <th scope="col">Gesuchter Stoff&nbsp;</th>
			  </tr>~n'
			),
        format('<tr>~n<td>~k</td>~n', Anzahl),
        format('<td>~k</td>~n<tr>~n', Stoff),
        format('</table>'),
	    format('<hr>~n', []),
	    \+minimaleSammlungLoesung(Anzahl, Stoff) -> format('<h4>Stoff kann nicht hergestellt werden</h4>'); true/* */
        .

